sudo: required
services:
  - "docker"

before_install:
  - docker build -t jomag/docker-react -f Dockerfile.dev .

script:
  - docker run jomag/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-708178337788"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
